### ISSUE TITLE
Docs feedback on planning-questionnaire

### ISSUE THREAD

**Issue by grantmiller** [replicatedhq/replicated-docs#1303]
URL: https://docs.replicated.com/vendor/planning-questionnaire
Feedback details: this questionnaire should probably move down to  a different category "distributing your application"

**Comment by dhavens-dev** [comment]
@chris-sanders tagging you here as this is a page we need to re-write. Do you have a story or GitHub issue to track the work?

**Comment by chris-sanders** [comment]
@dhavens-dev Yes tracked here: https://app.shortcut.com/replicated/story/80408/update-onboarding-questionnaire
Diamon and I reviewed some recommendations today, we also came to the conclusion a different approach to planning is probably better. The questionnaire might be best as a template during onboarding instead. He's looking at it.

**Comment by paigecalvert** [comment]
We'll work with Diamon on this, too. 👍 

And @chris-sanders --The docs team is focusing in Q3 on lots of onboarding improvements, so if there's any "bigger picture" changes that go beyond this planning questionnaire that you all would like to see, let us know.

**Comment by chris-sanders** [comment]
@paigecalvert  Absolutely there is!

* We've recently created a dedicated examples repository: https://github.com/replicatedhq/platform-examples
* We're going to adjust the starter repo: https://github.com/replicatedhq/replicated-starter-helm so that it becomes a clean template to get started from rather than a mix of examples and templates.

With the managed onboarding offerings, we're looking to take what we learn and give people a better set of guidance to get started from. All helm based, reference the full app examples above, etc. If you're looking at Q3 we'll keep working on getting raw examples and templates setup and let's sync over a larger plan when it's on the horizon and you're ready to start planning out the changes.

**Comment by paigecalvert** [comment]
@chris-sanders awesome! sounds great. I'll set a reminder for myself to follow up with you on this post-launch :)

**Comment by paigecalvert** [comment]
Also, I'm going to close out this issue since conversation is also ongoing in the related story as well as the related PR: https://github.com/replicatedhq/replicated-docs/pull/1297
