### ISSUE TITLE
Docs feedback on install-with-helm

### ISSUE THREAD

**Issue by AmberAlston** [replicatedhq/replicated-docs#1305]
https://docs.replicated.com/vendor/install-with-helm
Feedback details: May already be in the works, but just calling out need for updates as I'm reviewing Helm/SDK docs again

- Show Helm Install Tab feature flag is also mentioned here: https://docs.replicated.com/vendor/install-with-helm#prerequisites
- The screenshot under Install item 2 says "...install Alpha KOTS using Helm". I'm guessing that's what the app was named "Example to install Alpha KOTS" in this example, but it's super confusing that we are saying "alpha kots" here.

**Comment by jonquil2002** [comment]
The entitlement is removed with PR https://github.com/replicatedhq/replicated-docs/pull/1318

@AmberAlston   The screenshot is going to be harder because there is a bug with preflights that prevents us from getting an updated screenshot. The VP team is aware of the bug (https://replicated.slack.com/archives/CEEFDQURM/p1689638387705739). I'll follow-up with them on Monday to see about getting this updated. If you feel it's a deal breaker for the launch, lmk and I'll remove the screenshot altogether for now.

**Comment by AmberAlston** [comment]
Let's remove the screenshot for now and have a follow up story to add it back once we can get a better one. Thanks!

**Comment by paigecalvert** [comment]
I replaced the screenshot with this one of the helm install instructions button:
![helm-install-button](https://github.com/replicatedhq/replicated-docs/assets/11523028/9a0b8dbf-b172-40a2-9985-4f2e8edd14de)
