### ISSUE TITLE
Docs feedback on kots-cli-install

### ISSUE THREAD

**Issue by sj-porter-knime** [replicatedhq/replicated-docs#1618]
The KOTS CLI docs seem to be somewhat hidden? I haven't paged through every option but it seems/feels like you can't get to [these docs](https://docs.replicated.com/reference/kots-cli-install#usage) without searching for them. Other CLIs are documented and accessible from the docs homepage (e.g. Replicated CLI) under the "DEVELOPER TOOLS" section.

**Comment by paigecalvert** [comment]
So true @sj-porter-knime ... what do you think about something like this? https://deploy-preview-1619--replicated-docs.netlify.app/

![Screenshot 2023-11-14 at 12 52 19 PM](https://github.com/replicatedhq/replicated-docs/assets/11523028/e8394942-d821-47e5-873f-4b18e9273d21)

It would add a "reference" type link to the main Developer Tools section that takes you over to the kots CLI docs.

For context, the reason that the kots CLI docs were in that other section is because the kots CLI is used by the "enterprise user" persona to install/manage with KOTS. That said, of course a developer working with the Replicated platform to distribute their app with KOTS would need to interact with the kots CLI to test their installation workflow, etc.

So, I was thinking this solution could be a good way to serve both audiences by keeping the kots CLI docs in the "Install and Manage with KOTS" section, while also adding a reference to them in the Developer Tools section so that it's easier to find. What do you think?

**Comment by sj-porter-knime** [comment]
Sounds great to me, Paige!

**Comment by paigecalvert** [comment]
Nice! I'll merge it in 👍 Thanks for the feedback

**Comment by paigecalvert** [comment]
Closing with https://github.com/replicatedhq/replicated-docs/pull/1619
