### ISSUE TITLE
https://docs.replicated.com/enterprise/installing-existing-cluster-automation

### ISSUE THREAD

**Issue by Clauther-N** [replicatedhq/replicated-docs#1659]
URL: 
Feedback details:
Could you be more clear on automation ?
Is it possible to run preflight checks and deploy an application from the command line (without using the admin console) ?

**Comment by paigecalvert** [comment]
Hi @Clauther-N , apologies for missing this issue.

Yes, you can run preflight checks and deploy an application from the command line without using the admin console. In the case of installing with automation from the command line, the preflight check results are displayed in the CLI output rather than being displayed in the admin console. So, if you run any of the commands on the [Installing with Automation](https://docs.replicated.com/enterprise/installing-existing-cluster-automation) page of the docs, then preflight checks will automatically run before the app is installed.

For a specific example of how this looks, you can check out this tutorial: https://docs.replicated.com/vendor/tutorial-cli-install-app-manager

**Comment by paigecalvert** [comment]
Additionally, I can certainly clarify in the docs that preflight checks _do_ still run when you install from the command line. Thanks for your feedback!

**Comment by paigecalvert** [comment]
Hi @Clauther-N , with the linked PR this docs page is updated to:
* Clarify that preflight checks run from the CLI during an automated install with the kots CLI
* Include an example of `kots install` output
* A link to the tutorial that I mentioned above that provides a walkthrough of how to do an automated install with a sample app

Closing out this issue. Let me know if you have any other questions or docs requests!
