### ISSUE TITLE
Docs feedback on installing-embedded-cluster

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/replicated-docs#622]
https://docs.replicated.com/enterprise/installing-embedded-cluster#air-gap

Suggests that the only way to do the airgap install is with the KOTS CLI, but this can also be completed through the UI

**Comment by paigecalvert** [comment]
Thanks @dexhorthy. Reviewing this procedure, it looks like it's actually incorrect, too. The following paragraph appears below step 2, where users run the `kots install` command:

>After the installation command finishes, note the Kotsadm and Login with password (will not be shown again) fields in the output of the installation command. Then, log in to the admin console to complete the application setup, run preflight checks, and deploy. See [Completing Application Setup and Deploying](https://docs.replicated.com/enterprise/installing-app-setup).

I believe this is incorrect because:
- the `Kotsadm` and `Login with password (will not be shown again)` fields would actually appear after the user runs the curl command in step 1, not after step 2
- the `kots install` command in step 2 actually already has them take care of all the steps that they would do to install the app from the admin console UI, so it's wrong to put that paragraph _after_ having them run the kots install command in step 2

**Comment by paigecalvert** [comment]
Story: https://app.shortcut.com/replicated/story/58430/air-gap-install-on-embedded-cluster-procedure-incorrect

**Comment by paigecalvert** [comment]
@dexhorthy, we addressed this feedback with https://github.com/replicatedhq/replicated-docs/pull/640, which has been merged.

I'm going to close this issue, but please take a look and let us know if there's anything else we can do to better address your feedback.

Thanks again!
