### ISSUE TITLE
replicated delete command is not working 

### ISSUE THREAD

**Issue by ayyappa-yb** [replicatedhq/replicated-docs#690]
Feedback details: when I try "replicated app delete app-name" the error message is "Error: App not found".

**Comment by paigecalvert** [comment]
Hi @ayyappa-yb , thank you for reaching out and apologies for the delay in responding.

The Replicated Documentation team triages the issues in this repo, and we are not able to advise on issues or errors that you are seeing in the product itself. Rather, we advise and address any feedback about issues with the content on this docs site.

That said, I am not sure if either of these are helpful to you, but some initial thoughts that I have are to try running `replicated app ls` to see the full list of app names and make sure you have the right one. Or, I also wonder if you have the necessary RBAC policy assigned to you in the vendor portal to be able to delete an app. You could check the assigned policy on the Team Members page: https://vendor.replicated.com/team/members

If you have not already been able to resolve this, I'd recommend that you reach out to your account rep for additional help troubleshooting this error message that you're seeing. They should be able to help point you in the right direction.

Also, you may have already tried these resources, but just to share in case not: In the future if you run into similar issues when using the product and docs.replicated.com does not have the answer, you could try reviewing the [Replicated Community](https://community.replicated.com/) site to see if your question might have already been addressed there. If not, you could post your question to the Community site to ask for help.

Thanks again for reaching out, and hopefully this is helpful. I am going to close this out since this repository is not the best place for troubleshooting product issues, though please do let me know if any of the above does not make sense. I am happy to clarify where I can.
