### ISSUE TITLE
Docs feedback on updating kots

### ISSUE THREAD

**Issue by segaldan** [replicatedhq/replicated-docs#833]
URL: https://docs.replicated.com/enterprise/updating-embedded-cluster
Feedback details:
`$ curl -sSL https://kurl.sh/supergoodtool | sudo bash
Password:
bash: line 1: {error:{message:The requested installer does not exist}}: command not found`

**Comment by jonquil2002** [comment]
@segeldan Thank you for letting us know this topic needs updating. Can you try running the command with your APP_SLUG instead of `supergoodtool`?

So it would be `$ curl -sSL https://kurl.sh/APP_SLUG | sudo bash` and replace `APP_SLUG` with your application slug from the **Settings** page in the vendor portal.

I'll open an PR to fix this issue in the docs and let you know when it is corrected. Please let us know if you have further questions or issues. Thanks again.

**Comment by jonquil2002** [comment]
Hi. I've opened this PR to fix it; it's under technical  review right now. https://github.com/replicatedhq/replicated-docs/pull/839.

**Comment by jonquil2002** [comment]
Hi, @segaldan Just want to let you know this issue has been fixed and the documentation should be much clearer now. If you have any other questions, please let us know. Thanks again for helping to improve the docs!
